# Services Definition
# https://github.com/compose-spec/compose-spec/blob/master/spec.md
services:

  db:
    # ***************************************************************************
    # Postgres Database
    #
    # Relational Database
    #
    # Repository:
    # https://github.com/postgres/postgres
    container_name: db

    # Package Stored on Docker Hub
    # https://hub.docker.com/_/mysql
    image: postgres:16-alpine

    # Restart Container Unless Stopped
    restart: unless-stopped

    # Networks
    networks:
      # Internal Database Network
      - postgres

    # Storage Volumes
    volumes:
      # Data Directory
      - postgres_data:/var/lib/postgresql/data:rw

    # Environment Variables
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    # Health Check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

    # Container Labels
    labels:
      # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      # Traefik Labels - see https://doc.traefik.io/traefik/routing/providers/docker/
      # Disable Traefik Discovery
      - "traefik.enable=false"
      # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      # Watchtower Labels - see https://containrrr.dev/watchtower/running-multiple-instances/
      # Watchtower Scope - Update Daily
      - "com.centurylinklabs.watchtower.scope=daily"
      # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # ***************************************************************************