# Services Definition
# https://github.com/compose-spec/compose-spec/blob/master/spec.md
services:

  docker-proxy:
    # ***************************************************************************
    # Docker Socket Proxy
    #
    # Proxies requests to the Docker socket to prevent external attacks.
    #
    # Repository:
    # https://github.com/Tecnativa/docker-socket-proxy
    extends:
      file: docker-proxy.yml
      service: docker-proxy
    # ***************************************************************************

  watchtower-daily:
    # ***************************************************************************
    # Watchtower Daily
    #
    # Updates Docker containers with latest published versions. Runs once daily.
    #
    # Repository:
    # https://github.com/containrrr/watchtower
    extends:
      file: watchtower-daily.yml
      service: watchtower-daily

    # Startup Dependencies
    depends_on:
      - docker-proxy
    # ***************************************************************************

  traefik:
    # ***************************************************************************
    # Traefix Proxy Router
    #
    # Published At:
    # https://traefik.dev.russfeld.me
    #
    # Repository:
    # https://github.com/traefik/traefik
    extends:
      file: traefik.yml
      service: traefik

    # Startup Dependencies
    depends_on:
      - docker-proxy
    # ***************************************************************************

  watchtower-webhook:
    # ***************************************************************************
    # Watchtower Webhook
    #
    # Updates Docker containers with latest published versions. Runs when triggered
    # via a webhook ping.
    #
    # Published At:
    # https://watchtower.dev.russfeld.me
    #
    # Repository:
    # https://github.com/containrrr/watchtower
    extends:
      file: watchtower-webhook.yml
      service: watchtower-webhook

    # Startup Dependencies
    depends_on:
      - traefik
      - docker-proxy
    # ***************************************************************************

  js-docker:
    # ***************************************************************************
    # JS Docker Example
    #
    # Published At:
    # https://js.dev.russfeld.me
    #
    # Repository:
    # https://github.com/russfeld/docker-examples
    extends:
      file: js-docker.yml
      service: js-docker

    # Startup Dependencies
    depends_on:
      - traefik
      - db
    # ***************************************************************************

  py-docker:
    # ***************************************************************************
    # JS Docker Example
    #
    # Published At:
    # https://py.dev.russfeld.me
    #
    # Repository:
    # https://github.com/russfeld/docker-examples
    extends:
      file: py-docker.yml
      service: py-docker

    # Startup Dependencies
    depends_on:
      - traefik
      - db
    # ***************************************************************************

networks:
  # External Network Routed by Traefik
  traefik:
    name: traefik
  # Internal Network to Attach to docker-proxy
  docker-proxy:
    name: docker-proxy
    internal: 
  postgres:
    name: postgres
    internal:

volumes:
  postgres_data: