entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
  metrics:
    address: ":8082"
certificatesResolvers:
  letsencrypt:
    acme:
      email: russfeldh@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
providers:
  docker:
    exposedByDefault: false
    watch: true
    endpoint: "tcp://docker-proxy:2375"
    network: "docker-proxy"
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true
api:
  dashboard: true