CREATE TABLE users (
  id     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name   varchar(40) NOT NULL CHECK (name <> ''),
  eid    varchar(20) NOT NULL CHECK (name <> '')
);

INSERT INTO users (name, eid) VALUES 
  ('Russell Feldhausen', 'russfeld'),
  ('Nathan Bean', 'nhbean'),
  ('Josh Weese', 'weeser');
  
SELECT * FROM users;